# Generated by Django 5.2.7 on 2025-12-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comment_threads_and_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_link',
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
