# Generated by Django 5.2.7 on 2025-12-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_post_downvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downvote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
