# Generated by Django 5.2.7 on 2025-12-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_counts_and_comment_downvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdownvote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
